//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherFeather.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForecastPeriod
    {
        public int ForecastPeriodID { get; set; }
        public int ForecastID { get; set; }
        public int Symbol { get; set; }
        public string WindDirection { get; set; }
        public decimal Temperature { get; set; }
        public decimal AirPressure { get; set; }
        public decimal WindSpeed { get; set; }
        public decimal Percipitation { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Forecast Forecast { get; set; }
    }
}
