//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherFeather.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecast
    {
        public Forecast()
        {
            this.ForecastPeriod = new HashSet<ForecastPeriod>();
        }
    
        public int ForecastID { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<ForecastPeriod> ForecastPeriod { get; set; }
    }
}
