//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherFeather.Models.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wp12_jb222rw_weatherEntities : DbContext
    {
        public wp12_jb222rw_weatherEntities()
            : base("name=wp12_jb222rw_weatherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Forecast> Forecast { get; set; }
        public DbSet<ForecastPeriod> ForecastPeriod { get; set; }
    }
}
